import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
RESOURCES_DIR = BASE_DIR / "resources"
DATA_DIR = BASE_DIR / "data"
DB_DIR = BASE_DIR / "db"
OUTPUTS_DIR = BASE_DIR / "outputs"
EVALUATION_DIR = BASE_DIR / "evaluation"
RESOURCE_DOCUMENTS_DIR = RESOURCES_DIR / "documents"
RESOURCE_DATASETS_DIR = RESOURCES_DIR / "datasets"
IMAGE_OUTPUT_DIR = OUTPUTS_DIR / "images"
TABLE_OUTPUT_DIR = OUTPUTS_DIR / "tables"
PAGE_IMAGE_DIR = OUTPUTS_DIR / "page_images"
PATCH_OUTPUT_DIR = OUTPUTS_DIR / "patches"
PATCH_ATTRIBUTION_DIR = OUTPUTS_DIR / "patch_attributions"

CANONICAL_PDF_PATH = RESOURCE_DOCUMENTS_DIR / "ifc-annual-report-2024-financials.pdf"
LEGACY_PDF_PATH = DATA_DIR / "ifc-annual-report-2024-financials.pdf"
PDF_PATH = CANONICAL_PDF_PATH if CANONICAL_PDF_PATH.exists() else LEGACY_PDF_PATH
FAISS_INDEX_PATH = DB_DIR / "faiss_index"
PHASE6_FAISS_INDEX_PATH = DB_DIR / "phase6_patch_faiss_index"
QDRANT_LOCAL_PATH = DB_DIR / "qdrant"
QDRANT_COLLECTION = "ifc_annual_report_2024"
PHASE6_QDRANT_COLLECTION = "ifc_annual_report_2024_phase6_patches"
SEMANTIC_CACHE_PATH = DB_DIR / "semantic_cache.json"
PHASE6_PATCH_STORE_PATH = DB_DIR / "phase6_patch_store.json"
PHASE6_PATCH_EMBEDDINGS_PATH = DB_DIR / "phase6_patch_embeddings.npy"
PHASE6_PATCH_TOKEN_EMBEDDINGS_PATH = DB_DIR / "phase6_patch_token_embeddings.json"
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")

EMBEDDING_MODEL = "models/gemini-embedding-001"
LLM_MODEL = "gemini-2.0-flash"
CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
EMBEDDING_BATCH_SIZE = 250
TOP_K = 5
RETRIEVAL_CANDIDATES = 12
HYBRID_CANDIDATES = 16
HYBRID_RERANK_LIMIT = 10
SEMANTIC_CACHE_THRESHOLD = 0.93
SEMANTIC_CACHE_ENABLED = os.getenv("SEMANTIC_CACHE_ENABLED", "true").lower() == "true"
SEMANTIC_CACHE_VERSION = "2026-05-05-phase-cache-v4"

MIN_IMAGE_WIDTH = 96
MIN_IMAGE_HEIGHT = 96
MAX_PAGE_CONTEXT_CHARS = 1200
PHASE6_PATCH_MIN_TEXT_CHARS = 40
PHASE6_PATCH_CONTEXT_CHARS = 420
PHASE6_PAGE_RENDER_SCALE = 1.6
PHASE6_PATCH_PADDING = 8
PHASE6_TOP_K = 4
PHASE6_RETRIEVAL_CANDIDATES = 12

LANGFUSE_ENABLED = os.getenv("LANGFUSE_ENABLED", "true").lower() == "true"
LANGFUSE_PUBLIC_KEY = os.getenv("LANGFUSE_PUBLIC_KEY")
LANGFUSE_SECRET_KEY = os.getenv("LANGFUSE_SECRET_KEY")
LANGFUSE_HOST = os.getenv("LANGFUSE_HOST")

DEFAULT_EVAL_DATASET = DATA_DIR / "eval_questions.sample.json"
CANONICAL_PHASE2_EVAL_DATASET = RESOURCE_DATASETS_DIR / "rag_evaluation_dataset.csv"
LEGACY_PHASE2_EVAL_DATASET = EVALUATION_DIR / "RAG_evaluation_dataset.csv"
PHASE2_EVAL_DATASET = (
    CANONICAL_PHASE2_EVAL_DATASET
    if CANONICAL_PHASE2_EVAL_DATASET.exists()
    else LEGACY_PHASE2_EVAL_DATASET
)
EVAL_RESULTS_DIR = EVALUATION_DIR / "results"

RAGAS_TIMEOUT_SECONDS = 300
RAGAS_MAX_RETRIES = 3
RAGAS_MAX_WAIT_SECONDS = 30
RAGAS_MAX_WORKERS = 2
RAGAS_BATCH_SIZE = 4
RAGAS_ANSWER_RELEVANCY_STRICTNESS = 1
